### ISSUE TITLE
namespace OAuth2Authenticator could not be found

### ISSUE THREAD

**Issue by modydiop** [VIENNA-Advantage-ERP-CRM/official-VAFramework-ERP-CRM#921]
Hi there - I have finally decided to give VA a try.
I am getting loads of error in the GmailConfig class,- it complaining about OAuth2Authenticator (namespace not found).
Below are all the namespace loaded. 

Could you please guide me - thanks?

using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading;
using System.Web;
using DotNetOpenAuth.Messaging;
using DotNetOpenAuth.OAuth2;
using Google.Apis;
using Google.Apis.Calendar.v3;
using Google.Apis.Calendar.v3.Data;
using Google.Apis.Tasks.v1;
//using RestSharp.Authenticators;
using VAdvantage.DataBase;
using VAdvantage.Utility;

using Google.Apis.Oauth2;
using Google.Apis.Tasks.v1.Data;

**Comment by vivekk421** [comment]
Hi modydiop, 
You can use below google OAUTH namespaces to remove the errors.


![Namespace](https://user-images.githubusercontent.com/37937901/119348050-fdebe900-bcb9-11eb-98fe-9cf72ab357c8.PNG)

**Comment by modydiop** [comment]
Thanks.
